### ISSUE TITLE
GET all Reviews based on Product's Id

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#10]
GET `api/products/:productId/reviews'
Returns all the reviews that belong to a product specified by id.

- [x] Seed data exists in the database for reviews to be returned.
- [x] Successful response includes only reviews for the specified product
- [x] Review data returned includes the `id`, `userId`, `productId`, `description`, `itemRating`, `shippingRating`, `createdAt`, and `updatedAt`
- [x] Review data returns associated data for `User`, including the `id`, `firstName`, and `lastName`
- [x] Review data returns associated data for `ReviewImages`, an array of image data including the `id` and `url`
- [x] Error response with status 404 is given when a product does not exist with the provided `id`

**Comment by AlexJc23** [comment]
- [x]  Review data does not return data  for User, including the id, firstName, and lastName
- [x] The first review has images, the rest have empty lists not sure if this is purposely done due to images not being there...
- [x] An empty list is returned for a product_id that does not exist. instead of 404 error
